# Generated by Django 5.0.4 on 2024-04-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
